version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
